/* This file is automatically generated.  DO NOT EDIT! */
extern ld_emulation_xfer_type ld_elf_i386_emulation;
extern ld_emulation_xfer_type ld_elf_iamcu_emulation;

#define EMULATION_LIST \
  &ld_elf_i386_emulation, \
  &ld_elf_iamcu_emulation, \
  0
